name: prにコメントを足す
on:
  issue_comment:
    types: [ created ] # pr(またはissue)にコメントされたとき
jobs:
  add-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # このアクションを行わないとリポジトリ内のスクリプト等が参照できない。
      - name: 作成されたPRにコメントを足します
        run: ./scripts/02-add-pr-comment.sh ${{ github.event.pull_request.number }}
