name: prにコメントを足す
on:
  pull_request_review_comment:
    types: [ created ] # prにコメントされたとき
  pull_request:
    types: [ edited ]
jobs:
  add-pr-comment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ghコマンドを使うため
    steps:
      - uses: actions/checkout@v2 # このアクションを行わないとリポジトリ内のスクリプト等が参照できない。
      - name: 作成されたPRにコメントを足します
        run: ./scripts/02-add-pr-comment.sh ${{ github.event.pull_request.number }}
