name: マーケットプレイスのアクション実行
on:
  schedule:
    - cron: "0 3 * * *" 
    # 毎日12:00に実行する
  workflow_dispatch:
jobs:
  update-waka-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: d5e8d16990ee4951bbc1512d97bb54a4
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
